import json
from datetime import datetime, timezone
from specfoundry_schema import STAGES

PLACEHOLDERS = {"yes", "no", "n/a", "na", "tbd", "unknown", "works", "good", "better"}


def vague(value, minimum=24):
    return not isinstance(value, str) or len(value.strip()) < minimum or value.lower().strip() in PLACEHOLDERS


def validate_stage(stage, answers):
    errors = []
    for key, kind, label, _ in stage["fields"]:
        value = answers.get(key)
        if kind in {"textarea", "text"} and vague(value, 12 if kind == "text" else 24):
            errors.append(f"{label} is still too vague to serve as an engineering decision.")
        elif kind in {"environments", "memory", "actions"} and not value:
            errors.append(f"{label} requires at least one selection.")
        elif kind == "number" and (value is None or int(value) < 1):
            errors.append(f"{label} must be greater than zero.")
    if stage["id"] == "success":
        text = (str(answers.get("success_state", "")) + " " + str(answers.get("verifier", ""))).lower()
        if "independent" not in text and "external" not in text and "test" not in text and "human" not in text:
            errors.append("Describe an independent or externally checkable verification mechanism.")
    if stage["id"] == "memory" and answers.get("memory_types") and vague(answers.get("invalidation", "")):
        errors.append("Persistent memory requires explicit invalidation and conflict rules.")
    return errors


def all_stage_errors(answers):
    return {stage["id"]: validate_stage(stage, answers) for stage in STAGES}


def derived_items(answers):
    out = {"requirements": [], "risks": [], "assumptions": [], "open": []}
    if answers.get("ground_truth"):
        out["requirements"].append("Important outcomes must be checked against declared ground-truth sources.")
    if answers.get("termination"):
        out["requirements"].append("Every run needs bounded stop, retry, and escalation semantics.")
    if answers.get("memory_types"):
        out["requirements"].append("Persistent memory needs explicit write, retrieval, verification, and invalidation rules.")
    if answers.get("action_classes"):
        out["risks"].append("Action permissions, approval rules, verification, and recovery must be testable by action class.")
    if answers.get("baseline"):
        out["assumptions"].append("The declared baseline can attempt the target task distribution and will be measured before added mechanisms are credited with improvement.")
    if answers.get("llm_decisions"):
        out["assumptions"].append("The observation and context interface exposes enough information for the model to make the declared decisions.")
    open_text = str(answers.get("open_questions", "")).strip()
    if open_text and open_text.lower() not in {"none", "no open questions", "n/a"}:
        out["open"].append(open_text)
    return out


def readiness(answers):
    errors = all_stage_errors(answers)
    passed = sum(not errors[s["id"]] for s in STAGES)
    pct = round(100 * passed / len(STAGES))
    return pct, errors, passed == len(STAGES) and not derived_items(answers)["open"]


def markdown_spec(answers):
    lines = ["# Engineering Specification", "", f"Generated by SpecFoundry on {datetime.now(timezone.utc).isoformat()}", ""]
    for stage in STAGES:
        lines += [f"## {stage['title']}", ""]
        for key, _, label, _ in stage["fields"]:
            value = answers.get(key, "")
            if isinstance(value, list):
                value = ", ".join(value)
            lines += [f"### {label}", "", str(value).strip() or "_Unresolved_", ""]
    derived = derived_items(answers)
    for title, key in [("Derived requirements", "requirements"), ("Derived risks", "risks"), ("Explicit assumptions", "assumptions"), ("Open critical questions", "open")]:
        lines += [f"## {title}", ""]
        lines += [f"- {item}" for item in derived[key]] or ["- None identified."]
        lines.append("")
    pct, errors, ready = readiness(answers)
    lines += ["## Readiness", "", f"- Score: **{pct}%**", f"- Implementation ready: **{'YES' if ready else 'NO'}**", ""]
    blockers = [s["title"] for s in STAGES if errors[s["id"]]]
    if blockers:
        lines += ["### Blocking stages", ""] + [f"- {name}" for name in blockers] + [""]
    return "\n".join(lines)


def json_spec(answers):
    pct, errors, ready = readiness(answers)
    return json.dumps({"generated_at": datetime.now(timezone.utc).isoformat(), "answers": answers, "derived": derived_items(answers), "readiness": {"score": pct, "implementation_ready": ready, "blocking": {k: v for k, v in errors.items() if v}}}, indent=2)
